### ISSUE TITLE
Den Spidy-Beinen mehr Kraft geben, damit der Spidy selber aufstehen kann

### ISSUE THREAD

**Issue by rzstaakenRalf** [rzstaaken/SpidyPy#3]
1. Versuche machen und messen welcher Strom im Betrieb von den Servos gezogen wird.

usw.

**Comment by rzstaakenRalf** [comment]
Die ersten Versuche haben ergeben, die Leitungen der Spannungsversorgung ist zu dünn.
Am Eingang geht der Strom bei Belastung bis auf 2 Ampere hoch. Im selben Moment bricht die Spannung am letzten Servo bis auf 2 V zusammen. (Der Controller ist für 5V ausgelegt )
Weitere Versuche werde ich in den nächsten Tagen machen.

**Comment by alphasoft** [comment]
Test, test, issue #0815, bitte beheben! :-)

**Comment by alphasoft** [comment]
Test des Zugriffs weiterer gitHub-Teilnehmer => erfolgreich

**Comment by rzstaakenRalf** [comment]
Dank Grit schafft es jetzt der Spidy aufzustehen.
 Beine dicht an dem Körper, dann geht es nach oben!
